# fish completion for openclaw

complete -c openclaw -n "__fish_use_subcommand" -a "completion setup onboard configure config backup doctor dashboard reset uninstall message mcp agent agents status health sessions tasks acp gateway daemon logs system models infer approvals exec-policy nodes devices node sandbox tui cron dns docs proxy hooks webhooks qr clawbot browser memory pairing plugins channels directory security secrets skills update -V --container --dev --profile --log-level --no-color" -d 'OpenClaw command or global option'

complete -c openclaw -n "__fish_seen_subcommand_from completion" -a "-s -i --write-state -y" -d 'Options for completion'
complete -c openclaw -n "__fish_seen_subcommand_from setup" -a "--workspace --wizard --non-interactive --mode --remote-url --remote-token" -d 'Options for setup'
complete -c openclaw -n "__fish_seen_subcommand_from onboard" -a "--workspace --reset --reset-scope --non-interactive --accept-risk --flow --mode --auth-choice --token-provider --token --token-profile-id --token-expires-in --secret-input-mode --cloudflare-ai-gateway-account-id --cloudflare-ai-gateway-gateway-id --alibaba-model-studio-api-key --anthropic-api-key --arceeai-api-key --openrouter-api-key --byteplus-api-key --chutes-api-key --cloudflare-ai-gateway-api-key --deepseek-api-key --fal-api-key --fireworks-api-key --gemini-api-key --huggingface-api-key --kilocode-api-key --kimi-code-api-key --litellm-api-key --lmstudio-api-key --minimax-api-key --mistral-api-key --moonshot-api-key --openai-api-key --opencode-zen-api-key --opencode-go-api-key --qianfan-api-key --modelstudio-standard-api-key-cn --modelstudio-standard-api-key --modelstudio-api-key-cn --modelstudio-api-key --runway-api-key --stepfun-api-key --synthetic-api-key --together-api-key --venice-api-key --ai-gateway-api-key --volcengine-api-key --vydra-api-key --xai-api-key --xiaomi-api-key --zai-api-key --custom-base-url --custom-api-key --custom-model-id --custom-provider-id --custom-compatibility --gateway-port --gateway-bind --gateway-auth --gateway-token --gateway-token-ref-env --gateway-password --remote-url --remote-token --tailscale --tailscale-reset-on-exit --install-daemon --no-install-daemon --skip-daemon --daemon-runtime --skip-channels --skip-skills --skip-search --skip-health --skip-ui --node-manager --json" -d 'Options for onboard'
complete -c openclaw -n "__fish_seen_subcommand_from configure" -a "--section" -d 'Options for configure'
complete -c openclaw -n "__fish_seen_subcommand_from config" -a "get set unset file schema validate --section" -d 'Options for config'
complete -c openclaw -n "__fish_seen_subcommand_from backup" -a "create verify" -d 'Options for backup'
complete -c openclaw -n "__fish_seen_subcommand_from doctor" -a "--no-workspace-suggestions --yes --repair --fix --force --non-interactive --generate-gateway-token --deep" -d 'Options for doctor'
complete -c openclaw -n "__fish_seen_subcommand_from dashboard" -a "--no-open" -d 'Options for dashboard'
complete -c openclaw -n "__fish_seen_subcommand_from reset" -a "--scope --yes --non-interactive --dry-run" -d 'Options for reset'
complete -c openclaw -n "__fish_seen_subcommand_from uninstall" -a "--service --state --workspace --app --all --yes --non-interactive --dry-run" -d 'Options for uninstall'
complete -c openclaw -n "__fish_seen_subcommand_from message" -a "send broadcast poll react reactions read edit delete pin unpin pins permissions search thread emoji sticker role channel member voice event timeout kick ban" -d 'Options for message'
complete -c openclaw -n "__fish_seen_subcommand_from mcp" -a "serve list show set unset" -d 'Options for mcp'
complete -c openclaw -n "__fish_seen_subcommand_from agent" -a "-m -t --session-id --agent --thinking --verbose --channel --reply-to --reply-channel --reply-account --local --deliver --json --timeout" -d 'Options for agent'
complete -c openclaw -n "__fish_seen_subcommand_from agents" -a "list bindings bind unbind add set-identity delete" -d 'Options for agents'
complete -c openclaw -n "__fish_seen_subcommand_from status" -a "--json --all --usage --deep --timeout --verbose --debug" -d 'Options for status'
complete -c openclaw -n "__fish_seen_subcommand_from health" -a "--json --timeout --verbose --debug" -d 'Options for health'
complete -c openclaw -n "__fish_seen_subcommand_from sessions" -a "cleanup --json --verbose --store --agent --all-agents --active" -d 'Options for sessions'
complete -c openclaw -n "__fish_seen_subcommand_from tasks" -a "list audit maintenance show notify cancel flow --json --runtime --status" -d 'Options for tasks'
complete -c openclaw -n "__fish_seen_subcommand_from acp" -a "client --url --token --token-file --password --password-file --session --session-label --require-existing --reset-session --no-prefix-cwd --provenance -v" -d 'Options for acp'
complete -c openclaw -n "__fish_seen_subcommand_from gateway" -a "run status install uninstall start stop restart call usage-cost health probe discover --port --bind --token --auth --password --password-file --tailscale --tailscale-reset-on-exit --allow-unconfigured --dev --reset --force --verbose --cli-backend-logs --claude-cli-logs --ws-log --compact --raw-stream --raw-stream-path" -d 'Options for gateway'
complete -c openclaw -n "__fish_seen_subcommand_from daemon" -a "status install uninstall start stop restart" -d 'Options for daemon'
complete -c openclaw -n "__fish_seen_subcommand_from logs" -a "--limit --max-bytes --follow --interval --json --plain --no-color --local-time --url --token --timeout --expect-final" -d 'Options for logs'
complete -c openclaw -n "__fish_seen_subcommand_from system" -a "event heartbeat presence" -d 'Options for system'
complete -c openclaw -n "__fish_seen_subcommand_from models" -a "list status set set-image aliases fallbacks image-fallbacks scan auth --status-json --status-plain --agent" -d 'Options for models'
complete -c openclaw -n "__fish_seen_subcommand_from infer" -a "list inspect model image audio tts video web embedding" -d 'Options for infer'
complete -c openclaw -n "__fish_seen_subcommand_from approvals" -a "get set allowlist" -d 'Options for approvals'
complete -c openclaw -n "__fish_seen_subcommand_from exec-policy" -a "show preset set" -d 'Options for exec-policy'
complete -c openclaw -n "__fish_seen_subcommand_from nodes" -a "status describe list pending approve reject rename invoke notify push canvas camera screen location" -d 'Options for nodes'
complete -c openclaw -n "__fish_seen_subcommand_from devices" -a "list remove clear approve reject rotate revoke" -d 'Options for devices'
complete -c openclaw -n "__fish_seen_subcommand_from node" -a "run status install uninstall stop restart" -d 'Options for node'
complete -c openclaw -n "__fish_seen_subcommand_from sandbox" -a "list recreate explain" -d 'Options for sandbox'
complete -c openclaw -n "__fish_seen_subcommand_from tui" -a "--url --token --password --session --deliver --thinking --message --timeout-ms --history-limit" -d 'Options for tui'
complete -c openclaw -n "__fish_seen_subcommand_from cron" -a "status list add rm enable disable runs run edit" -d 'Options for cron'
complete -c openclaw -n "__fish_seen_subcommand_from dns" -a "setup" -d 'Options for dns'
complete -c openclaw -n "__fish_seen_subcommand_from docs" -a "" -d 'Options for docs'
complete -c openclaw -n "__fish_seen_subcommand_from proxy" -a "start run coverage sessions query blob purge" -d 'Options for proxy'
complete -c openclaw -n "__fish_seen_subcommand_from hooks" -a "list info check enable disable install update" -d 'Options for hooks'
complete -c openclaw -n "__fish_seen_subcommand_from webhooks" -a "gmail" -d 'Options for webhooks'
complete -c openclaw -n "__fish_seen_subcommand_from qr" -a "--remote --url --public-url --token --password --setup-code-only --no-ascii --json" -d 'Options for qr'
complete -c openclaw -n "__fish_seen_subcommand_from clawbot" -a "qr" -d 'Options for clawbot'
complete -c openclaw -n "__fish_seen_subcommand_from browser" -a "status start stop reset-profile tabs tab open focus close profiles create-profile delete-profile screenshot snapshot navigate resize click type press hover scrollintoview drag select upload waitfordownload download dialog fill wait evaluate console pdf responsebody highlight errors requests trace cookies storage set --browser-profile --json --url --token --timeout --expect-final" -d 'Options for browser'
complete -c openclaw -n "__fish_seen_subcommand_from memory" -a "status index search promote promote-explain rem-harness rem-backfill" -d 'Options for memory'
complete -c openclaw -n "__fish_seen_subcommand_from pairing" -a "list approve" -d 'Options for pairing'
complete -c openclaw -n "__fish_seen_subcommand_from plugins" -a "list inspect enable disable uninstall install update doctor marketplace" -d 'Options for plugins'
complete -c openclaw -n "__fish_seen_subcommand_from channels" -a "list status capabilities resolve logs add remove login logout" -d 'Options for channels'
complete -c openclaw -n "__fish_seen_subcommand_from directory" -a "self peers groups" -d 'Options for directory'
complete -c openclaw -n "__fish_seen_subcommand_from security" -a "audit" -d 'Options for security'
complete -c openclaw -n "__fish_seen_subcommand_from secrets" -a "reload audit configure apply" -d 'Options for secrets'
complete -c openclaw -n "__fish_seen_subcommand_from skills" -a "search install update list info check" -d 'Options for skills'
complete -c openclaw -n "__fish_seen_subcommand_from update" -a "wizard status --json --no-restart --dry-run --channel --tag --timeout --yes" -d 'Options for update'
